#!/bin/bash
git rm src/app/components/modal-gsm/ALogin.ts
git rm src/app/components/modal-gsm/modal-gsm.component.css
git rm src/app/components/modal-gsm/modal-gsm.component.html
git rm src/app/components/modal-gsm/modal-gsm.component.ts
git rm projects/gsm2/src/assets/libs/cycle2/jquery.cycle2.carousel.min.js
git rm projects/gsm2/src/assets/libs/cycle2/jquery.cycle2.js.map
git rm projects/gsm2/src/assets/libs/cycle2/jquery.cycle2.min.js
git rm projects/gsm2/src/assets/libs/cycle2/jquery.cycle2.swipe.min.js
git rm projects/gsm2/src/assets/libs/lightcase/css/lightcase.css
git rm projects/gsm2/src/assets/libs/lightcase/fonts/lightcase.eot
git rm projects/gsm2/src/assets/libs/lightcase/fonts/lightcase.svg
git rm projects/gsm2/src/assets/libs/lightcase/fonts/lightcase.ttf
git rm projects/gsm2/src/assets/libs/lightcase/fonts/lightcase.woff
git rm projects/gsm2/src/assets/libs/lightcase/js/jquery.events.touch.js
git rm projects/gsm2/src/assets/libs/lightcase/js/lightcase.js
git rm projects/gsm2/src/assets/libs/lightcase/scss/components/_settings.scss
git rm projects/gsm2/src/assets/libs/lightcase/scss/components/fonts/_font-lightcase.scss
git rm projects/gsm2/src/assets/libs/lightcase/scss/components/mixins/_presets.scss
git rm projects/gsm2/src/assets/libs/lightcase/scss/components/mixins/_utilities.scss
git rm projects/gsm2/src/assets/libs/lightcase/scss/components/modules/_animations.scss
git rm projects/gsm2/src/assets/libs/lightcase/scss/components/modules/_case.scss
git rm projects/gsm2/src/assets/libs/lightcase/scss/components/modules/_content.scss
git rm projects/gsm2/src/assets/libs/lightcase/scss/components/modules/_error.scss
git rm projects/gsm2/src/assets/libs/lightcase/scss/components/modules/_global.scss
git rm projects/gsm2/src/assets/libs/lightcase/scss/components/modules/_info.scss
git rm projects/gsm2/src/assets/libs/lightcase/scss/components/modules/_loading.scss
git rm projects/gsm2/src/assets/libs/lightcase/scss/components/modules/_navigation.scss
git rm projects/gsm2/src/assets/libs/lightcase/scss/components/modules/_overlay.scss
git rm projects/gsm2/src/assets/libs/lightcase/scss/lightcase.scss
git rm projects/gsm2/src/assets/libs/linceform/captcha/CaptchaSecurityImages.php
git rm projects/gsm2/src/assets/libs/linceform/captcha/CaptchaSecurityImagesNewsletter.php
git rm projects/gsm2/src/assets/libs/linceform/captcha/gpl.txt
git rm projects/gsm2/src/assets/libs/linceform/captcha/monofont.ttf
git rm projects/gsm2/src/assets/libs/linceform/captcha/monofont_read_me.txt
git rm projects/gsm2/src/assets/libs/linceform/linceform.css
git rm projects/gsm2/src/assets/libs/linceform/linceform.min.js
git rm projects/gsm2/src/assets/libs/owl/owl.carousel.css
git rm projects/gsm2/src/assets/libs/owl/owl.js
git rm projects/gsm2/src/assets/libs/owl/owl.theme.default.css
git rm projects/gsm2/src/assets/libs/owl/owl.video.play.png
git rm projects/gsm2/src/assets/libs/prefixfree/prefixfree.min.js
git rm projects/gsm2/src/assets/libs/wow/animate.min.css
git rm projects/gsm2/src/assets/libs/wow/wow.min.js
